import json
import logging
import os

import google.generativeai as genai

logger = logging.getLogger(__name__)
genai.configure(api_key=os.getenv("GEMINI_API_KEY"))
PRIMARY_MODEL = os.getenv("GEMINI_PRIMARY_MODEL", "gemini-2.5-flash")
OLLAMA_PRIMARY_MODEL = os.getenv("OLLAMA_PRIMARY_MODEL", "llama3")

SYSTEM_PROMPT = """
You are a precise factual assistant. Your job is to answer questions
accurately AND provide an honest self-assessment of your confidence.

Respond ONLY as valid JSON with this exact structure:
{
  "answer": "Your complete, well-reasoned answer here",
  "confidence": 82,
  "reasoning": "Brief explanation of your confidence level"
}

Confidence scoring rules:
- 90-100: Mathematical facts, universal scientific laws, verified historical events
- 75-89: Well-documented facts with broad consensus
- 50-74: Partial knowledge, some uncertainty, topic may have conflicting info
- 25-49: Limited knowledge, significant uncertainty
- 0-24: Largely unknown to you - say so clearly in the answer

CRITICAL: Be genuinely honest about uncertainty. Overconfident wrong answers
are worse than honest uncertainty. Never score above 75 for niche topics,
recent events, or anything you are not fully certain about.
Most topics should score 60-80. Reserve 90+ for absolute certainties only.
Confidence reflects your certainty about factual accuracy, not your
completeness or answer length.
"""


class PrimaryLLMError(RuntimeError):
    def __init__(self, message: str, failure_type: str = "provider_unavailable"):
        super().__init__(message)
        self.failure_type = failure_type


def _classify_primary_failure(message: str) -> str:
    lower = message.lower()

    if any(marker in lower for marker in ["quota", "rate limit", "429", "resource exhausted", "retry_delay"]):
        return "quota_exceeded"
    if any(marker in lower for marker in ["timed out", "timeout", "deadline exceeded"]):
        return "timeout"
    if any(marker in lower for marker in ["malformed json", "response invalid", "json"]):
        return "malformed_response"
    return "provider_unavailable"


async def call_primary(query: str) -> dict:
    """
    Calls Gemini with JSON mode enforced.
    Returns {"answer": str, "confidence": int, "reasoning": str}.
    """
    try:
        model = genai.GenerativeModel(
            model_name=PRIMARY_MODEL,
            system_instruction=SYSTEM_PROMPT,
        )
        response = await model.generate_content_async(
            query,
            generation_config=genai.GenerationConfig(
                temperature=0.3,
                max_output_tokens=800,
                response_mime_type="application/json",
            ),
        )
        result = json.loads(response.text)

        assert "answer" in result, "Missing 'answer' field"
        assert "confidence" in result, "Missing 'confidence' field"
        assert 0 <= result["confidence"] <= 100, f"Confidence out of range: {result['confidence']}"

        logger.info(
            f"Primary LLM ({PRIMARY_MODEL}) | confidence={result['confidence']} | query_len={len(query)}"
        )
        return result
    except json.JSONDecodeError as e:
        logger.error(f"Primary LLM JSON parse error: {e}")
        raise PrimaryLLMError("Primary LLM returned malformed JSON", "malformed_response") from e
    except AssertionError as e:
        logger.error(f"Primary LLM response validation failed: {e}")
        raise PrimaryLLMError(f"Primary LLM response invalid: {str(e)}", "malformed_response") from e
    except Exception as e:
        logger.error(f"Primary LLM API error: {e}")
        failure_type = _classify_primary_failure(str(e))
        raise PrimaryLLMError(f"Primary LLM failed: {str(e)}", failure_type) from e


async def call_ollama_primary(query: str) -> dict:
    import httpx

    prompt = (
        "You are a careful factual assistant. Answer the user's question directly and concisely. "
        "If you are uncertain, say so plainly.\n\n"
        f"Question: {query}"
    )

    try:
        async with httpx.AsyncClient(timeout=30) as client:
            response = await client.post(
                "http://localhost:11434/api/generate",
                json={
                    "model": OLLAMA_PRIMARY_MODEL,
                    "prompt": prompt,
                    "stream": False,
                    "options": {"temperature": 0.2},
                },
            )
            response.raise_for_status()
            data = response.json()
    except Exception as e:
        logger.warning(f"Ollama primary fallback failed: {e}")
        raise PrimaryLLMError(f"Ollama fallback failed: {str(e)}") from e

    answer = data.get("response", "").strip()
    if not answer:
        raise PrimaryLLMError("Ollama fallback returned empty response")

    logger.info(f"Primary fallback (Ollama {OLLAMA_PRIMARY_MODEL}) | answer_len={len(answer)}")
    return {
        "answer": answer,
        "confidence": 35,
        "reasoning": "Generated by a local fallback model after the primary provider failed.",
    }
